
  create table "public"."memories" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null default auth.uid(),
    "chat_id" uuid not null,
    "title" text not null,
    "content" text not null,
    "category" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."memories" enable row level security;


  create table "public"."memory_sections" (
    "id" bigint generated always as identity not null,
    "memory_id" bigint not null,
    "chunk_index" integer not null,
    "content" text not null,
    "embedding" vector(1536),
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."memory_sections" enable row level security;

CREATE INDEX memories_category_idx ON public.memories USING btree (category);

CREATE INDEX memories_chat_id_idx ON public.memories USING btree (chat_id);

CREATE UNIQUE INDEX memories_pkey ON public.memories USING btree (id);

CREATE INDEX memories_user_id_idx ON public.memories USING btree (user_id);

CREATE INDEX memory_sections_embedding_idx ON public.memory_sections USING hnsw (embedding vector_ip_ops) WITH (m='16', ef_construction='64');

CREATE UNIQUE INDEX memory_sections_memory_id_chunk_index_key ON public.memory_sections USING btree (memory_id, chunk_index);

CREATE UNIQUE INDEX memory_sections_pkey ON public.memory_sections USING btree (id);

alter table "public"."memories" add constraint "memories_pkey" PRIMARY KEY using index "memories_pkey";

alter table "public"."memory_sections" add constraint "memory_sections_pkey" PRIMARY KEY using index "memory_sections_pkey";

alter table "public"."memories" add constraint "memories_chat_id_fkey" FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE not valid;

alter table "public"."memories" validate constraint "memories_chat_id_fkey";

alter table "public"."memories" add constraint "memories_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."memories" validate constraint "memories_user_id_fkey";

alter table "public"."memory_sections" add constraint "memory_sections_memory_id_chunk_index_key" UNIQUE using index "memory_sections_memory_id_chunk_index_key";

alter table "public"."memory_sections" add constraint "memory_sections_memory_id_fkey" FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE not valid;

alter table "public"."memory_sections" validate constraint "memory_sections_memory_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_memory_and_chunks(p_user_id uuid, p_chat_id uuid, p_title text, p_content text, p_category text, p_chunks jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_memory_id BIGINT;
BEGIN
  -- Insert new memory
  INSERT INTO memories (
    user_id, 
    chat_id,
    title, 
    content, 
    category
  )
  VALUES (
    p_user_id, 
    p_chat_id,
    p_title, 
    p_content, 
    p_category
  )
  RETURNING id INTO v_memory_id;
  
  -- Insert chunks
  INSERT INTO memory_sections (memory_id, chunk_index, content, embedding)
  SELECT 
    v_memory_id,
    (chunk->>'chunk_index')::INT,
    chunk->>'content',
    (chunk->>'embedding')::vector(1536)
  FROM jsonb_array_elements(p_chunks) AS chunk;
  
  RETURN v_memory_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.match_user_memories(query_embedding vector, match_threshold double precision DEFAULT 0.7, match_count integer DEFAULT 5, p_user_id uuid DEFAULT auth.uid())
 RETURNS TABLE(id bigint, content text, title text, category text, similarity double precision)
 LANGUAGE plpgsql
 STABLE
AS $function$
BEGIN
  RETURN QUERY
  SELECT 
    ms.id,
    ms.content,
    m.title,
    m.category,
    (ms.embedding <#> query_embedding) * -1 AS similarity
  FROM memory_sections ms
  JOIN memories m ON ms.memory_id = m.id
  WHERE m.user_id = p_user_id
    AND ms.embedding <#> query_embedding < -match_threshold
  ORDER BY ms.embedding <#> query_embedding
  LIMIT match_count;
END;
$function$
;

grant delete on table "public"."memories" to "anon";

grant insert on table "public"."memories" to "anon";

grant references on table "public"."memories" to "anon";

grant select on table "public"."memories" to "anon";

grant trigger on table "public"."memories" to "anon";

grant truncate on table "public"."memories" to "anon";

grant update on table "public"."memories" to "anon";

grant delete on table "public"."memories" to "authenticated";

grant insert on table "public"."memories" to "authenticated";

grant references on table "public"."memories" to "authenticated";

grant select on table "public"."memories" to "authenticated";

grant trigger on table "public"."memories" to "authenticated";

grant truncate on table "public"."memories" to "authenticated";

grant update on table "public"."memories" to "authenticated";

grant delete on table "public"."memories" to "service_role";

grant insert on table "public"."memories" to "service_role";

grant references on table "public"."memories" to "service_role";

grant select on table "public"."memories" to "service_role";

grant trigger on table "public"."memories" to "service_role";

grant truncate on table "public"."memories" to "service_role";

grant update on table "public"."memories" to "service_role";

grant delete on table "public"."memory_sections" to "anon";

grant insert on table "public"."memory_sections" to "anon";

grant references on table "public"."memory_sections" to "anon";

grant select on table "public"."memory_sections" to "anon";

grant trigger on table "public"."memory_sections" to "anon";

grant truncate on table "public"."memory_sections" to "anon";

grant update on table "public"."memory_sections" to "anon";

grant delete on table "public"."memory_sections" to "authenticated";

grant insert on table "public"."memory_sections" to "authenticated";

grant references on table "public"."memory_sections" to "authenticated";

grant select on table "public"."memory_sections" to "authenticated";

grant trigger on table "public"."memory_sections" to "authenticated";

grant truncate on table "public"."memory_sections" to "authenticated";

grant update on table "public"."memory_sections" to "authenticated";

grant delete on table "public"."memory_sections" to "service_role";

grant insert on table "public"."memory_sections" to "service_role";

grant references on table "public"."memory_sections" to "service_role";

grant select on table "public"."memory_sections" to "service_role";

grant trigger on table "public"."memory_sections" to "service_role";

grant truncate on table "public"."memory_sections" to "service_role";

grant update on table "public"."memory_sections" to "service_role";


  create policy "Users can delete their own memories"
  on "public"."memories"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = user_id));



  create policy "Users can insert their own memories"
  on "public"."memories"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Users can update their own memories"
  on "public"."memories"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id));



  create policy "Users can view their own memories"
  on "public"."memories"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "Users can delete their own memory sections"
  on "public"."memory_sections"
  as permissive
  for delete
  to authenticated
using ((memory_id IN ( SELECT memories.id
   FROM memories
  WHERE (memories.user_id = auth.uid()))));



  create policy "Users can insert memory sections"
  on "public"."memory_sections"
  as permissive
  for insert
  to authenticated
with check ((memory_id IN ( SELECT memories.id
   FROM memories
  WHERE (memories.user_id = auth.uid()))));



  create policy "Users can view their own memory sections"
  on "public"."memory_sections"
  as permissive
  for select
  to authenticated
using ((memory_id IN ( SELECT memories.id
   FROM memories
  WHERE (memories.user_id = auth.uid()))));



